### ISSUE TITLE
Define how to handle `null` type 

### ISSUE THREAD

**Issue by jonaslagoni** [json-schema-org/vocab-idl#15]
We need to figure out how we want to handle the `null` type overall.

**Comment by jdesrosiers** [comment]
In JSON, `null` is a different concept than "not present" and the types we generate need to reflect that. In most languages, `null` or `nil` is synonymous with "not present". In those languages I would expect code gen to use a custom type that represents the JSON `null` value.

**Comment by jonaslagoni** [comment]
So, for `null` I am not quite sure what is best. If we look at the behavior JSON schema has on the JSON data.

JSON Schema:
```json
{ "properties": { "test": { "type": "null" } } }
```
validates correctly against 
```json
{ "test": null }
```
and
```json
{  }
```
In a sense, removing the property completely makes sense to some extend here, as there are no values you want to access is there? 


However, with require, removing the property is not possible and it needs to be present:
```json
{ "required": ["test"], "properties": { "test": { "type": "null" } } }
```
validates correctly against 
```json
{ "test": null }
```
but not
```json
{  }
```

In a sense, we have the same scenario anyway, where you don't really have an incentive to access such as property in any use-case is there (besides when the class is serialized the property needs to be there)?

In TS we can do the following:
```ts
class testType {
  test: null
}
```
And for Java:
```Java
class testType {
  final Object test = null;
}
```

We could also let custom serializable functionality handle it, and not generate the property at all:
```ts
class testType {
  serialize(){
    return '{test: null}'
  }
}
```

I do however find that a bit weird 🤔 What are your thoughts?

**Comment by jonaslagoni** [comment]
Alright, that makes sense 👍 Thanks for clarifying 🙂

**Comment by gregsdennis** [comment]
I realize this has been closed for a while, but I thought this was relevant.

`null` is also important in how many APIs handle 'PUT' and even `PATCH` requests.  For these APIs, `{ "test": null }` means "clear the `test` property, whereas `{ }` means do nothing.

*In some API frameworks (like what's offered out of the box by .Net), this is difficult to discern, though, because they treat `null` and "absent" as the same when deserializing JSON into models.*
